### ISSUE TITLE
check-bugs.py fails with a stacktrace

### ISSUE THREAD

**Issue by nixpanic** [gluster/release-tools#6]
```
Traceback (most recent call last):
  File "./check-bugs.py", line 352, in <module>
    bs.verifyState()
  File "./check-bugs.py", line 211, in verifyState
    changeStatus = change.getExpectedBugStatus()
  File "./check-bugs.py", line 147, in getExpectedBugStatus
    if self.isForQA():
  File "./check-bugs.py", line 130, in isForQA
    if not self.resolveTag():
  File "./check-bugs.py", line 121, in resolveTag
    if not self.resolveCommit():
  File "./check-bugs.py", line 117, in resolveCommit
    self.commit = self.repo.findCommit(self.created, self.branch, self.changeid)
  File "./check-bugs.py", line 57, in findCommit
    commit = subprocess.check_output(cmd, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'git log --format=raw --after='2015-04-08 09:07:36.907000000' origin/master | grep -E -e '^commit [[:alnum:]]+$' -e '^[[:space:]]*Change-Id:' | grep -B1 '^[[:space:]]*Change-Id: I2b6503ad9333f445ebdcd9fa660da20b861b985f$'' returned non-zero exit status 1
```

The executed command does not return any commits. A search in Gerrit for this Change-Id results in one change: http://review.gluster.org/10158

I'm not yet sure what the problem is...

**Comment by nixpanic** [comment]
This does not happen anymore :+1:
